### ISSUE TITLE
Fix the binary build issue on Windows

### ISSUE THREAD

**Issue by phargogh** [natcap/ROOT#5]
When Jade was doing a training recently, the ROOT application launched, but then there was an issue at runtime.  We suspect this was a binary import issue and only on Windows (Peter ran ROOT on mac and had no issues). 

- [x] dig out the bug report and confirm the nature of the bug
- [ ] Fix the issue

**Comment by phargogh** [comment]
I had implemented the binary builds, so this feels like a thing I should have checked for in #1 .

**Comment by phargogh** [comment]
Here are two the two logfiles from Jade. 
[InVEST-ROOT-log-2021-04-07--15_34_24.txt](https://github.com/natcap/ROOT/files/6480917/InVEST-ROOT-log-2021-04-07--15_34_24.txt)
[InVEST-ROOT-log-2021-04-07--16_06_13.txt](https://github.com/natcap/ROOT/files/6480918/InVEST-ROOT-log-2021-04-07--16_06_13.txt)

The real feature of them is the missing `PROJ.db` which is affecting a warp on what looks like it might be the sample data.  Should be an easy enough fix.

```
2021-04-07 15:34:24,984 utils._log_gdal_errors(80) ERROR [errno 1] PROJ: proj_create_from_database: Cannot find proj.db
2021-04-07 15:34:24,985 utils._log_gdal_errors(80) ERROR [errno 1] PROJ: proj_create_from_database: Cannot find proj.db
2021-04-07 15:34:25,005 utils._log_gdal_errors(80) ERROR [errno 1] PROJ: proj_identify: Cannot find proj.db
2021-04-07 15:34:25,711 utils._log_gdal_errors(80) ERROR [errno 1] PROJ: proj_identify: Cannot find proj.db
2021-04-07 15:34:25,764 utils._log_gdal_errors(80) ERROR [errno 1] PROJ: proj_identify: Cannot find proj.db
2021-04-07 15:34:28,470 utils._log_gdal_errors(80) ERROR [errno 1] PROJ: proj_create_from_database: Cannot find proj.db
2021-04-07 15:34:28,472 utils._log_gdal_errors(80) ERROR [errno 1] PROJ: proj_create_from_database: Cannot find proj.db
2021-04-07 15:34:28,516 utils._log_gdal_errors(80) ERROR [errno 1] PROJ: proj_create_from_database: Cannot find proj.db
2021-04-07 15:34:28,517 utils._log_gdal_errors(80) ERROR [errno 1] PROJ: proj_create_from_database: Cannot find proj.db
2021-04-07 15:34:28,556 utils._log_gdal_errors(80) ERROR [errno 1] PROJ: proj_create_from_database: Cannot find proj.db
2021-04-07 15:34:28,557 utils._log_gdal_errors(80) ERROR [errno 1] PROJ: proj_create_from_database: Cannot find proj.db
2021-04-07 15:34:28,576 utils._log_gdal_errors(80) ERROR [errno 1] PROJ: proj_identify: Cannot find proj.db
2021-04-07 15:34:28,772 utils._log_gdal_errors(80) ERROR [errno 5] D:/ROOT/05_root_outputs/01_potatoes_ic\ipm_01_potatoes_ndr.tif, band 1: Access window out of range in RasterIO().  Requested (0,1024) of size 256x186 on raster of 503x1209.
2021-04-07 15:34:28,775 utils._log_gdal_errors(80) ERROR [errno 5] D:/ROOT/05_root_outputs/01_potatoes_ic\ipm_01_potatoes_ndr.tif, band 1: Access window out of range in RasterIO().  Requested (256,1024) of size 247x186 on raster of 503x1209.
2021-04-07 15:34:28,777 model._logged_target(1652) ERROR Exception while executing <function execute at 0x0000025A34A6DCA8>
Traceback (most recent call last):
  File "natcap\invest\ui\model.py", line 1649, in _logged_target
  File "natcap\root\root.py", line 219, in execute
  File "natcap\root\preprocessing.py", line 167, in execute
  File "natcap\root\preprocessing.py", line 567, in _aggregate_marginal_values
TypeError: 'NoneType' object is not subscriptable
2021-04-07 15:34:28,778 model._logged_target(1655) INFO Execution finished
2021-04-07 15:34:28,779 utils.prepare_workspace(129) INFO Elapsed time: 4.53s
```

**Comment by phargogh** [comment]
Duplicate of #4
