### ISSUE TITLE
KeyError: activity_masks when doing preprocessing

### ISSUE THREAD

**Issue by phargogh** [natcap/ROOT#6]
Encountered while debugging #4 .

To reproduce, run ROOT (I used rev 2a672db, windows build), preprocessing only.  Datastack and logfile attached.

[KeyError-activity-masks.invest.tar.gz](https://github.com/natcap/ROOT/files/6804535/KeyError-activity-masks.invest.tar.gz)
[InVEST-ROOT-log-2021-07-12--14_33_25.txt](https://github.com/natcap/ROOT/files/6804537/InVEST-ROOT-log-2021-07-12--14_33_25.txt)

```text
2021-07-12 14:33:25,580 utils.prepare_workspace(123) INFO Writing log messages to C:\Users\jdouglass\Documents\root_workspace\InVEST-ROOT-log-2021-07-12--14_33_25.txt
2021-07-12 14:33:25,589 model._logged_target(1646) Level 100 Starting model with parameters: 
Arguments for InVEST __main__ 3.9.0:
combined_factor_table_path     C:/Users/jdouglass/Documents/ROOT_sample_data/04_root_input_tables/3_cf_table.csv
do_optimization                False
do_preprocessing               True
frontier_type                  
marginal_raster_table_path     C:/Users/jdouglass/Documents/ROOT_sample_data/04_root_input_tables/1_ipm_table.csv
n_workers                      -1
number_of_frontier_points      
objectives_table_path          
optimization_container         True
potential_conversion_mask_path C:/Users/jdouglass/Documents/ROOT_sample_data/01_activity_map_rasters/amr_01_potatoes.tif
preprocessing_container        True
results_suffix                 
serviceshed_shapefiles_table   C:/Users/jdouglass/Documents/ROOT_sample_data/04_root_input_tables/2_swm_table.csv
spatial_decision_unit_area     10
spatial_decision_unit_shape    C:\Users\jdouglass\Documents\ROOT_sample_data\03_spatial_weighted_maps\swm_sdu_grid.shp
targets_table_path             
workspace_dir                  C:\Users\jdouglass\Documents\root_workspace

2021-07-12 14:33:25,630 warnings._showwarnmsg(110) WARNING root.py:386: DeprecationWarning: 'U' mode is deprecated

2021-07-12 14:33:25,634 warnings._showwarnmsg(110) WARNING root.py:301: DeprecationWarning: 'U' mode is deprecated

2021-07-12 14:33:25,636 model._logged_target(1652) ERROR Exception while executing <function execute at 0x000002B6ACD28168>
Traceback (most recent call last):
  File "natcap\invest\ui\model.py", line 1649, in _logged_target
  File "natcap\root\root.py", line 221, in execute
  File "natcap\root\preprocessing.py", line 114, in execute
KeyError: 'activity_masks'
2021-07-12 14:33:25,637 model._logged_target(1655) INFO Execution finished
2021-07-12 14:33:25,639 utils.prepare_workspace(129) INFO Elapsed time: 0.06s
```

**Comment by phawthorne** [comment]
No longer occurring #16
